---
title: "DSCI 524: Collaborative Software Development"
---

How to exploit practices from collaborative software development techniques in data scientific workflows. Appropriate use of the software life cycle, unit testing / continuous integration, and packaging for use by others.

## Learning Outcomes

By the end of the course, students are expected to be able to:

-   complete a project that demonstrates appropriate use of collaborative software development processes and tools, including:
    -   packaging code for use by others, including the specification of dependencies/requirements
    -   using advanced distributed version control workflows and features (e.g., GitHub flow, master branch protection, code reviews, project boards and issue tracking) to effectively manage a multi-person project
    -   writing comprehensive test suites
    -   carrying out continuous integration via GitHub Actions
    -   deploying packaged software using semantic versioning
    -   writing clear and helpful documentation
    -   selecting software licenses that best suit the project
    -   critically evaluating work of others and providing constructive feedback

See [here](lecture_learning_objectives.md) for lecture-by-lecture learning objectives

## Teaching Team

| Section |         Position         |         Name         |      Slack Handle       |
|:-------:|:------------------------:|:--------------------:|:-----------------------:|
|   001   | Lecture & Lab Instructor |   Tiffany Timbers    |         `@tiff`         |
|   002   | Lecture & Lab Instructor |     Daniel Chen      | `@Daniel (Instructor)`  |

## Deliverables

This is a project-based course where you will work collaboratively in groups to develop a Python software package. In lecture and lab, we'll work on the skills and concepts that you need to learn to complete the project. You will work in randomly assigned groups of four for the project milestones. There are also some individual weekly assignments that act as stepping stones to the project milestones. Finally, because collaboration is so important in data science, we will be using a team work multiplier to adjust individual grades. A combination of peer evaluation and GitHub history will be used to evaluate this.

| Assessment                                                                                                            | weight                    | Deadline                |
|-----------------------------------------------------------------------------------------------------------------------|---------------------------|-------------------------|
| iClicker                                                                                                              | 3%                        | Every lecture           |
| Milestone 1: Coming up with a topic, and setting up package structure & function specification and documentation      | 15%                       | 2024-01-11 18:00 PT     |
| Individual assignment - Create your own toy Python and R packages (graded for completion)                             | 5%                        | 2024-01-11 18:00 PT     |
| Milestone 2: writing the code and tests for your package                                                              | 30%                       | 2024-01-18 18:00 PT     |
| Milestone 3: package documentation                                                                                    | 15%                       | 2024-01-26 11:59 PT     |
| Milestone 4: continuous integration (and deployment in the case of Python) and improve your package after peer review | 25%                       | **2024-02-03 23:59 PT** |
| Individual Peer review                                                                                                | 5%                        | **2024-01-30 23:59 PT** |
| Team work reflection                                                                                                  | 2%                        | **2024-02-04 23:59 PT** |
| Team work multiplier                                                                                                  | final grade \* multiplier | NA                      |

## Lecture Schedule - under construction!

Lecture notes: <https://ubc-dsci.github.io/reproducible-and-trustworthy-workflows-for-data-science/>

| Lecture | Topic                                                                                                             | Lecture notes                                                                                                                                                                                                                                                                             | Additional readings and resources                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
|---------|-------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 1       | Introduction to R & Python packages                                                                               | [Introduction to R & Python packages](https://ubc-dsci.github.io/reproducible-and-trustworthy-workflows-for-data-science/lectures/190-packaging-intro-python-r.html)                                                                                                                      | [Package structure and state (Python)](https://py-pkgs.org/04-package-structure#) & [Package structure and state (R)](https://r-pkgs.org/package-structure-state.html)                                                                                                                                                                                                                                                                                                                                                             |
| 2       | Introduction to collaborative software development                                                                | [Project management using GitHub](https://ubc-dsci.github.io/reproducible-and-trustworthy-workflows-for-data-science/lectures/060-version-control-3.html)                                                                                                                                 | [GitHub project boards](https://help.github.com/en/github/managing-your-work-on-github/about-project-boards), [GitHub project milestones](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones), [GitHub pull request reviews](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews), [About protected branches](https://docs.github.com/en/github/administering-a-repository/about-protected-branches) |
| 3       | PyTest                                                                                                            | [Pytest](https://ubc-dsci.github.io/reproducible-and-trustworthy-workflows-for-data-science/lectures/194-package-testing-python-pytest.html)                                                                                                                                              | [Testing in Python](https://py-pkgs.org/05-testing), [`pytest` docs](https://docs.pytest.org/en/latest/)                                                                                                                                                                                                                                                                                                                                                                                                                           |
| 4       | Testing coverage                                                                                                  | [Code coverage](https://ubc-dsci.github.io/reproducible-and-trustworthy-workflows-for-data-science/lectures/197-coverage-python.html)                                                                                                                                                     | TBD                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| 5       | Continuous integration (CI) via GitHub Actions                                                                    | [Continuous Integration](https://ubc-dsci.github.io/reproducible-and-trustworthy-workflows-for-data-science/lectures/200-continuous-integration.html) [CI+Python](https://ubc-dsci.github.io/reproducible-and-trustworthy-workflows-for-data-science/lectures/201-case_study_python.html) | [GitHub Actions docs](h-ttps://help.github.com/en/actions), [Github actions with R](https://ropenscilabs.github.io/actions_sandbox/packageci.html), [Continuous integration (Python)](https://py-pkgs.org/08-ci-cd#ci-cd-tools)                                                                                                                                                                                                                                                                                                    |
| 6       | Continuous deployment, versioning & package documentation                                                         | [CD: Python Documentation](https://ubc-dsci.github.io/reproducible-and-trustworthy-workflows-for-data-science/lectures/205-package_documentation_python.html)                                                                                                                             | [Semantic versioning](https://semver.org/), [R: Object Documentation](https://r-pkgs.org/man.html), [R: Vignettes](https://r-pkgs.org/vignettes.html), [`pkgdown`](https://pkgdown.r-lib.org/), [Documentation (Python)](https://py-pkgs.org/06-documentation)                                                                                                                                                                                                                                                                     |
| 7       | Publishing your package on the package indices (CRAN & PyPI), and peer review of data science R & Python packages | [Package Publishing: Python](https://ubc-dsci.github.io/reproducible-and-trustworthy-workflows-for-data-science/lectures/211-gha_python.html)                                                                                                                                             | [rOpenSci Packages: Development, Maintenance, and Peer Review](https://devguide.ropensci.org/), [The pyOpenSci Developer Guide](https://www.pyopensci.org/software-peer-review/about/intro.html)                                                                                                                                                                                                                                                                                                                                   |
| 8       | Copyright & Licenses                                                                                              | [Copyright and Licenses](https://ubc-dsci.github.io/reproducible-and-trustworthy-workflows-for-data-science/lectures/220-licenses-and-copyright.html)                                                                                                                                     | [Who owns the code?](https://asp-software.org/misv_resources/business-articles/who-owns-the-code/)                                                                                                                                                                                                                                                                                                                                                                                                                                 |

## Textbooks:

-   [Python packages](https://py-pkgs.org/) by Tomas Beuzen and Tiffany Timbers
-   [R packages](https://r-pkgs.org/) by Hadley Wickham and Jenny Bryan

## Class Schedule & office hours

See [calendar](https://ubc-mds.github.io/calendar/).

## Policies

Students are expected to attend 100% of their scheduled lab hours and attendance will be taken at the beginning of each lab session. Students must make formal requests for academic concession in the event that they cannot attend a lab session by filling out this [academic concession form](https://github.com/UBC-MDS/UBC-MDS.github.io/blob/master/img/Template%20-%20In-Term%20Academic%20Concessions%20Self%20Declaration.pdf?raw=1) and sending it to the course instructor. Applying for academic concession does not promise the granting of academic concession. Each application will be evaluated in the context of [UBC's Academic concession policy](https://vancouver.calendar.ubc.ca/campus-wide-policies-and-regulations/academic-concession). Students missing more than 25% of the total scheduled lab hours for a course without having received an academic concession will receive a possible maximum course grade of 50% and an “F” standing for the course on the transcript.

For all other policies, please see the general [MDS policies](https://ubc-mds.github.io/policies/).

------------------------------------------------------------------------

Authors: Tiffany A. Timbers, Varada Koltahar, Florencia D'Andrea, Daniel Chen

## License:

Software licensed under the [MIT License](https://spdx.org/licenses/MIT.html), non-software content licensed under the [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0) License](https://creativecommons.org/licenses/by-nc-sa/4.0/). See the [license file](LICENSE.md) for more information.
